name: AssembleOnMain

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  assemble:
    environment: env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Get secret and add to freshly created local.properties
        env:
          API_KEY: ${{secrets.PAYLIKE_MERCHANT_API_KEY}}
        run: |
          echo "PAYLIKE_MERCHANT_API_KEY=\"$API_KEY\"" >> local.properties
      - name: Build APK
        run: ./gradlew build
